name: Build Agenda APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK 35
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Descargar Gradle 8.7
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Compilar APK
        run: |
          gradle --version
          gradle assembleDebug --stacktrace

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Agenda-Personal-APK
          path: app/build/outputs/apk/debug/app-debug.apk
